### ISSUE TITLE
@GetMapping, @PostMapping, @DeleteMapping etc doesn't work as expected

### ISSUE THREAD

**Issue by JorgenRingen** [kongchen/swagger-maven-plugin#472] opened 2017-05-19 10:36 UTC
When using the new mapping-annotations from Spring 4.3 (@GetMapping, @PostMapping, etc...) the plugin doesn't seem to work. It only works with the standard @RequestMapping annotation.

Example:
@RequestMapping(value = "hello", method = RequestMethod.GET) <- works
@GetMapping("hello") <- doesn't work

Both annotations are equivalent and should work the same way (@GetMapping is actually the shorter and preferred way to declare mappings)

**Comment by timbuethe** [comment] 2017-06-12 14:09
This is a duplicate of https://github.com/kongchen/swagger-maven-plugin/issues/451

**Closed** 2017-06-12 21:59 UTC
