### ISSUE TITLE
Plugin doesn’t work with JDK 11

### ISSUE THREAD

**Issue by mirabilos** [kongchen/swagger-maven-plugin#688] opened 2018-11-20 17:55 UTC
And in contrast to #554 just adding the module won’t fly.

    [ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.7:generate (default) on project footool-services: Execution default of goal com.github.kongchen:swagger-maven-plugin:3.1.7:generate failed: A required class was missing while executing com.github.kongchen:swagger-maven-plugin:3.1.7:generate: javax/xml/bind/annotation/XmlRootElement

**Comment by mirabilos** [comment] 2018-11-20 18:09
Fixed by adding this to `<properties>`…

    <jaxb-substitute.api.version>1.0.4.Final</jaxb-substitute.api.version>

… and this to the swagger `<plugin>` tag in `<pluginManagement>`:

    <dependencies>
            <dependency>
                    <groupId>org.jboss.spec.javax.xml.bind</groupId>
                    <artifactId>jboss-jaxb-api_2.2_spec</artifactId>
                    <version>${jaxb-substitute.api.version}</version>
            </dependency>
    </dependencies>

**Comment by breun** [comment] 2018-12-12 09:59
Java 11 dropped JAXB from the JDK, so there will need to be a Maven artifact supplying those classes. I'd recommend using this dependency instead of the JBoss one, as recommended by http://openjdk.java.net/jeps/320:

```
<dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
    <version>2.3.1</version>
</dependency>
```

**Comment by mirabilos** [comment] 2018-12-12 10:49
Nils Breunese dixit:

>Java 11 dropped JAXB from the JDK, so there will need to be a Maven
>artifact supplying those classes. I'd recommend using this dependency
>instead of the JBoss one, as recommended by

Perhaps in the general case, but we have the JBoss ones already
in the project anyway and they work with less conflicts.

**Comment by albx79** [comment] 2018-12-27 12:43
Any feedback from the maintainers about my pull request?

Thanks

**Comment by jbotorek** [comment] 2018-12-27 14:11
I have also experienced problems with the plugin when running with Java11 - though, not related to the JAXB.
In my situation, the problem is with SQLException:
`[ERROR] Failed to execute goal com.github.kongchen:swagger-maven-plugin:3.1.7:generate (default) on project com.infor.ion.oneview.engine.rest: Execution default of goal com.github.kongchen:swagger-maven-plugin:3.1.7:generate failed: A required class was missing while executing com.github.kongchen:swagger-maven-plugin:3.1.7:generate: java/sql/SQLException`

Currently, the workaround is only to disable the plugin (setting the execution phase to _none_). 

Do you have any ideas how to overcome this, please?

**Comment by breun** [comment] 2018-12-28 00:54
@jbotorek Unlike the JAXB classes, `java.sql.SQLException` is still part of JDK 11: https://docs.oracle.com/en/java/javase/11/docs/api/java.sql/java/sql/SQLException.html

Do you use classpath or modulepath (JPMS) when running with Java 11? When using modules, you should include the `java.sql` module for that class.

**Comment by jbotorek** [comment] 2018-12-31 13:18
@breun , yes - that's the weird part - the java.sql package didn't changed in the j9-j11 changes at all... 
The project does not use modules. It's a maven-based application. See the attachment, please, for the plugin config.
[plugin_maven_config.txt](https://github.com/kongchen/swagger-maven-plugin/files/2718376/plugin_maven_config.txt)

I also noticed quite cryptic (for me at least) error message in the end of the output log:
```
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
```
Could this be any hint, please?

**Comment by albx79** [comment] 2019-01-03 13:31
No worries @jbotorek, I'm glad you figured it out.

@breun do you think my pull request could be merged?

**Closed** 2019-05-23 17:33 UTC
