### ISSUE TITLE
DTO inheritence is ignored by Swagger

### ISSUE THREAD

**Issue by itayavra** [kongchen/swagger-maven-plugin#256] opened 2015-11-24 10:33 UTC
Hey,
I'm trying to generate a python REST client based on Swagger documentation, using a swagger.json generated by swagger-maven-plugin-3.1.0
I have 2 DTOs that extend an abstract base class:

@ApiModel(subTypes = {FileSourceDTO.class, MemorySourceDTO.class}, discriminator = "classType")
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "classType")
@JsonSubTypes({
        @JsonSubTypes.Type(value = FileSourceDTO.class, name = "FileSourceDTO"),
        @JsonSubTypes.Type(value = MemorySourceDTO.class, name = "MemorySourceDTO") })
public abstract class LogSourceDTO implements BaseIdentifiableDTO<UUID>  {..}
@ApiModel(description = "FileSourceDTO", parent = LogSourceDTO.class)
publi` class FileSourceDTO extends LogSourceDTO {..}
@ApiModel(description = "MemorySourceDTO", parent = LogSourceDTO.class)
public class MemorySourceDTO extends LogSourceDTO {..}
In the resulting REST client, the FileSourceDTO and MemorySourceDTO classes don't contain a 'classType' field (which should be in the REST request as it is generated and expected by jackson) even though it should.

In addition, when I called (using the generated python REST client) an API method that returns an object of one of the children classes, an object of the abstract LogSourceDTO class was actually created instread (losing all the additional fields the children class adds over it).

I tried adding the above @ApiModel annotations (as you can see in the above example) since I found documentations suggesting that this is the solution, but it doesn't seem to solve this.
Am I doing something wrong?

Thanks,
Itay

**Comment by rakk** [comment] 2016-01-13 20:50
Hi Itay,

I got similar issue, forked, fixed and create pull request.
You can follow my pull request: https://github.com/kongchen/swagger-maven-plugin/pull/283
It would be helpful if you could confirm that my fork is solving your problem as well.
Simply build plugin locally and retest.

Best Regards,
Robert Kapala

**Comment by rakk** [comment] 2016-01-18 22:29
Code merged into master. Will be available in 3.1.3 version.

**Comment by rakk** [comment] 2016-02-17 09:03
3.1.3 is released.
Plaese close this issue.

**Closed** 2016-02-17 17:00 UTC

**Comment by thirionjl** [comment] 2016-04-04 17:28
Not sure this is completely related but the html file generated by the plugin does not show the subtype attributes (but the swagger.json is correct).

Generated swagger.json
```
"CompanyName" : {
      "allOf" : [ {
        "$ref" : "#/definitions/Name"
      }, {
        "type" : "object",
        "properties" : {
          "civility" : {
            "type" : "string",
            "example" : "#{model.CompanyName.civility.ex}",
            "description" : "#{model.CompanyName.civility.desc}",
            "readOnly" : true
          },
          "companyName" : {
            "type" : "string",
            "example" : "#{model.CompanyName.companyName.ex}",
            "description" : "#{model.CompanyName.companyName.desc}",
            "readOnly" : true
          },
          "contactName" : {
            "type" : "string",
            "example" : "#{model.CompanyName.contactName.ex}",
            "description" : "#{model.CompanyName.contactName.desc}",
            "readOnly" : true
          }
        }
      } ]
    }
```

Matching generated HTML:
```
## <a name="/definitions/CompanyName">CompanyName</a>

<table border="1">
    <tr>
        <th>name</th>
        <th>type</th>
        <th>required</th>
        <th>description</th>
        <th>example</th>
    </tr>
</table>
```

**Comment by rakk** [comment] 2016-05-09 05:06
Hi Jean-Luc,

Sorry for late reply.

I finally had a change to test 3.1.3 in our case and unfortunately not all
edge cases are covered.

The case you showed might be another non-covered case.
Personally I do not use html file so it is not the core functionality for
me.

Feel free to find the root cause, fix and create pull request.
This is how the open source works.

If you have any questions please do not hesitate to contact me.

Best Regards,
Robert Kapala



R
