### ISSUE TITLE
Add support for other SpringMVC annotations

### ISSUE THREAD

**Issue by aromanet42** [kongchen/swagger-maven-plugin#399] opened 2016-12-12 16:19 UTC
Hello,

it would be great if you can add support for Spring MVC annotations such as @GetMapping, @PostMapping, etc.

Thanks a lot

**Comment by clarkdo** [comment] 2017-01-09 08:05
+1

**Comment by Dema** [comment] 2017-01-28 19:48
Also, it would be good if plugin will complain if it found @ApiOperation annotation and not found @RequestMapping. I've just spent couple of hours trying to understand why it doesn't include on of my classes  into json.

**Comment by timbuethe** [comment] 2017-06-13 09:06
This is a duplicate of https://github.com/kongchen/swagger-maven-plugin/issues/451

**Comment by zbstof** [comment] 2018-03-12 13:59
Please close this, this is fixed as per 3.1.6

**Closed** 2019-05-22 13:52 UTC
