### ISSUE TITLE
does it works with swagger-springmvc?

### ISSUE THREAD

**Issue by imod** [kongchen/swagger-maven-plugin#19] opened 2013-10-04 08:07 UTC
Is it some how possible to get this to work with:
https://github.com/martypitt/swagger-springmvc ?

**Comment by reemdiab** [comment] 2015-01-18 14:03
Any news ?

**Comment by dilipkrish** [comment] 2015-01-18 15:54
Sorry, I've been working to get a 2.0 release of the [swagger-springmvc](https://github.com/martypitt/swagger-springmvc). One of the ideas I had was to generate documentation via a spring boot/mock mvc "test", probably not as lightweight, but it allows it to be design time concern rather than a runtime concern. I think the spring folks are adopting a similar idea in the [restdocs project](https://github.com/wilkinsona/spring-restdocs)

Anyhow, there is already a semblance of that in the current version, we added a [contract-tests module](https://github.com/martypitt/swagger-springmvc/tree/master/swagger-contract-tests) that we can possibly repurpose/repackage?

**Comment by leimer** [comment] 2015-01-18 16:55
I am under heavy load at work, so there was no time to push this issue any further.

@dilipkrish: I have a working solution here which uses the JUnit runner of Spring and the Spring MVC mock. I set up the original application context, but mock the environment dependent beans. This special configuration has to be provided by the user which is ugly but necessary.

The spring-restdocs sounds interesting. Perhaps this solves more than my solution and additionally has a more convenient approach.

**Comment by tedleman** [comment] 2015-01-20 20:04
Hi all,

I am sorry that I had to tease you for a few months when I said I had a solution for this. I have been extremely busy but will hopefully finishing the re-factoring of the plugin today. I was previously working with an older version of this plugin, but if you would like to see or test the changes they can be seen and tested with on my fork:

https://github.com/tedleman/swagger-maven-plugin

Essentially, I mimicked the jaxrs api reader with a behemoth class called SpringMvcApiReader, which generates an apiListing object. The entire thing works through the reflections api in order for it to generate during build time. This means that the reader creates api documentation that is a best estimate of how the service works based on annotations, methods, and fields in the controller  & model classes. The resources are derived from request mapping annotations, and the method I used for this was slightly specific to how my company standardizes mappings. I haven't had much of a chance to test it outside of our in-house service implementations.

Keep in mind that it may still be buggy, and may not be the solution that some of you are looking for. For example, if you are using data types that rely on spring runtime, such as model maps, it absolutely will not work because these cannot be properly read through reflections. 

If you would like to test it, clone my forked repo and add <springFramework>true</springFramework> to your <apiSource> configuration in the pom. @kongchen This is based on a slightly older version of the plugin, so I will review the changes you have made and make a pull request after I integrate them. 

Thanks,
Troy

**Comment by reemdiab** [comment] 2015-01-21 09:36
Thank you very much, waiting for the new version release with your changes :) !

**Comment by kongchen** [comment] 2015-01-21 14:31
Greate @tedleman . Look forward to your PR.

**Comment by WiSparky82** [comment] 2015-02-04 16:36
Hi, @kongchen. With @tedleman's merged PR, do you have an idea of when 2.3.3 might be finalized? Thanks!
Chris

**Comment by kongchen** [comment] 2015-02-05 02:24
Sorry, I was toooooooo busy in past weeks, I will try to take some time to
look at the PR and make the release this weekend.

2015-02-05 0:36 GMT+08:00 WiSparky82 <notifications@github.com>:

> Hi, @kongchen <https://github.com/kongchen>. With @tedleman
> <https://github.com/tedleman>'s merged PR, do you have an idea of when
> 2.3.3 might be finalized? Thanks!
> Chris
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kongchen/swagger-maven-plugin/issues/19#issuecomment-72888075>
> .
>



-- 
Regards,
Kong

**Comment by kongchen** [comment] 2015-02-08 16:12
Just released 2.3.3. 

And I use `supportSpringMvc` in configration instead of setting `swaggerApiReader` to enable SpringMvc support.

**Comment by robert-morschel** [comment] 2015-02-10 12:55
Hi,

What exactly does supportSpringMvc do?  For example if I used your  plugin on source with just Sprint REST annotations, would that yield anything useful?

I have tried this, without much luck.  I just get the basic:
{
  "apiVersion" : "1.0",
  "swaggerVersion" : "1.2",
  "basePath" : "http://example.com"
}

Regards,
Robert

**Comment by kongchen** [comment] 2015-02-10 13:51
@robert-morschel 
The version of springframework the plugin uses is`4.0.5.RELEASE`, is that different with yours?

**Comment by robert-morschel** [comment] 2015-02-10 14:52
I've changed the version from 3.1.1 to 4.0.5 but still no service are being picked up.

Is <locations> the package name of the classes where the plugin looks for services?  What Spring annotations are required for this work?  I'm using @Controller and @RequestMapping.

**Comment by tedleman** [comment] 2015-02-10 17:15
Hi Robert, are you also including @Api at the top of your controller classes?

**Comment by robert-morschel** [comment] 2015-02-11 08:22
Hi, 

No, I'm not.  We're not using any Swagger annotations at present, just the Spring ones.  I'm trying to assess what is minimally required to enable our existing Spring REST services for swagger.

**Comment by tedleman** [comment] 2015-02-11 19:23
That is odd, from your code snippet (with @Api included) there should have been at least one resource file for "samples". Can you post the output for the plugin's execution when you run a mvn install or mvn compile on the project?

**Comment by robert-morschel** [comment] 2015-02-12 08:42
[INFO] ------------------------------------------------------------------------
[INFO] Building restdoclet-sample 2.4.6-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.4:resources (default-resources) @ restdoclet-sample ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.0.2:compile (default-compile) @ restdoclet-sample ---
[INFO] Compiling 33 source files to C:\dev\projects\WebTrading\RESTdoclet\sample\target\classes
[INFO] 
[INFO] --- swagger-maven-plugin:2.3.3:generate (default) @ restdoclet-sample ---
[INFO] Creating file C:\dev\projects\WebTrading\RESTdoclet\sample\generated\swagger-ui\service.json
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.862s
[INFO] Finished at: Thu Feb 12 08:42:05 GMT 2015
[INFO] Final Memory: 20M/242M
[INFO] ------------------------------------------------------------------------

**Comment by robert-morschel** [comment] 2015-02-12 08:43
Configuration:
<pre>
<plugin>
            <groupId>com.github.kongchen</groupId>
            <artifactId>swagger-maven-plugin</artifactId>
            <version>2.3.3</version>
            <configuration>
                <apiSources>
                    <apiSource>
                        <locations>com.iggroup.oss.sample.web.controller</locations>
                        <apiVersion>1.0</apiVersion>
                        <basePath>http://example.com</basePath>
                        <swaggerDirectory>generated/swagger-ui</swaggerDirectory>
                        <supportSpringMvc>true</supportSpringMvc>
                    </apiSource>
                </apiSources>
            </configuration>
</pre>

**Comment by kongchen** [comment] 2015-02-12 09:18
What is the version of your swagger-core?

**Comment by robert-morschel** [comment] 2015-02-12 09:19
I only added an explicit Swagger dependency with the @API annotation, and that was to:
        <dependency>
            <groupId>com.wordnik</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>1.5.0-M1</version>
        </dependency>

**Comment by kongchen** [comment] 2015-02-12 09:26
Ah...Well, that's the root cause.

1.5.0-M1 is for Swagger Spec 2.0. Check https://github.com/swagger-api/swagger-core#compatibility for more details.

You should use version of 1.3.12 swagger-annotations which is for Swagger Spec 1.2 to compatible with this plugin.

We have 3.0-SNAPSHOT to support Swagger Spec 2.0 but it doesn't support SpringMvc yet.

**Comment by robert-morschel** [comment] 2015-02-12 09:37
Sadly that makes no difference.  Changed the version as you suggested and recompiled.  

Is my configuration correct?  I've assumed that the locations directive is the package in which my controllers live?

**Comment by robert-morschel** [comment] 2015-02-12 11:04
Interestingly, if I leave out: the supportSpringMvc line the plugin finds my @Api annotation and generates a foo.json.

**Comment by tedleman** [comment] 2015-02-12 16:26
Try adding a class-level @RequestMapping annotation, right after your @Controller. Even if you don't need the mapping see if @RequestMapping(value = "/") works.

**Comment by robert-morschel** [comment] 2015-02-12 16:33
No difference.
<pre>
/**
 * Sample Controller Controller for all sample REST services.
 */
@Api(value="foo")
@Component
@Controller("sampleController")
@RequestMapping(value = "/")
public class SampleController extends BaseController {

	@Autowired
	private SampleService service;

	/**
	 * Find sample by unique lookup reference
	 * 
	 * @param reference the sample reference, a 5 digit text field
	 * @return the sample object corresponding to the lookup reference
	 */
	@RequestMapping(value = "/samples/{reference}", method = {RequestMethod.GET})
	@ResponseBody
	public Sample getSampleByReference(@PathVariable String reference) {
...
</pre>

**Comment by robert-morschel** [comment] 2015-02-13 15:48
Got it to work.  Needs class level @Api and @RequestMapping and of course both to be the same.

**Comment by tinyrye** [comment] 2015-02-25 22:41
Had a couple of issues one of which required a change to your code:

In my (company's) use case the web service is centered around a business entity, let's call it 'Car'.  So there is a default controller with an empty base path '', or technically '/', as opposed a base path of let's say '/car'.

This caused two issues one of which is real minor and fixable in our code base:
1. My controller class required a @RequestMapping which wasn't a big deal and have a default base path which also isn't a big deal: simply add the annotation with @RequestMapping("/").
2. SpringMvcApiReader.generateBasePath runs into ArrayIndexOutOfBoundsException at line 154 in your project and line 141 in kongchen's project:
* `if(rPath.charAt(2)=='/'){`
* Parsing this default controller fails because rPath is either an empty string or 1-char long '/' which causes that exception.
* A code fix I employed is to check for string length of less than 2:
** `if (rPath.length() < 3) {
            // noop
        }`

Would you allow a code change that allows for an empty base path in the @RequestMapping?

**Comment by tinyrye** [comment] 2015-02-25 22:42
Otherwise a very easy tools to use, and viewing the source was rather easy to understand (so a thanks to kongchen is also in order!)

**Closed** 2015-03-31 08:00 UTC

**Comment by cirix** [comment] 2016-01-07 12:23
Guys I have the @Api annotation in class level but nothing happens...the swager json has only basic stuff read from plugin

**Comment by cirix** [comment] 2016-01-07 16:33
guys any suggestion if it can support multipackages the tool?also the springmvc doesnt' work for me...

**Comment by JorgenRingen** [comment] 2017-05-19 10:27
When using the @RequestMapping annotation in SpringMVC it works for me, but it doesn't work with the newer @GetMapping annotation.
